name: tag
on:
  push:
    tags:
      - "@joshuaavalon/*"
jobs:
  publish-react:
    name: publish:react
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/@joshuaavalon/eslint-config-react@')
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16.x
          registry-url: https://registry.npmjs.org
      - run: npm ci
      - run: npm publish --workspace @joshuaavalon/eslint-config-react
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
  publish-typescript:
    name: publish:typescript
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/@joshuaavalon/eslint-config-typescript@')
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16.x
          registry-url: https://registry.npmjs.org
      - run: npm ci
      - run: npm publish --workspace @joshuaavalon/eslint-config-typescript
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
